# Generated by Django 5.2.10 on 2026-01-19 22:28

import patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[patients.validators.validate_cpf]),
        ),
    ]
