# Generated by Django 5.2.10 on 2026-01-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_address_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
